/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2025-11-27T13:44:43.315659045+00:00
/// Collection: heroicons
/// This is a partial import from Iconify
/// Browse icons: https://icon-sets.iconify.design/heroicons/
///
/// ```yaml
/// total: 1288
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const ArrowLeft: IconData = IconData {
    name: "heroicons:arrow-left",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
