/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2025-11-27T11:59:06.007050361+00:00
/// Collection: mdi
/// This is a partial import from Iconify
/// Browse icons: https://icon-sets.iconify.design/mdi/
///
/// ```yaml
/// total: 7447
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Account: IconData = IconData {
    name: "mdi:account",
    body: r#"<path fill="currentColor" d="M12 4a4 4 0 0 1 4 4a4 4 0 0 1-4 4a4 4 0 0 1-4-4a4 4 0 0 1 4-4m0 10c4.42 0 8 1.79 8 4v2H4v-2c0-2.21 3.58-4 8-4"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Home: IconData = IconData {
    name: "mdi:home",
    body: r#"<path fill="currentColor" d="M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
