// Auto-generated by dioxus-iconify - DO NOT EDIT

use dioxus::prelude::*;

#[derive(Clone, Copy)]
pub struct IconData {
    pub name: &'static str,
    pub body: &'static str,
    pub view_box: &'static str,
    pub width: &'static str,
    pub height: &'static str,
}

#[component]
pub fn Icon(
    data: IconData,
    /// Additional attributes to extend the svg element
    #[props(extends = GlobalAttributes)]
    attributes: Vec<Attribute>,
) -> Element {
    rsx! {
        svg {
            view_box: "{data.view_box}",
            width: "{data.width}",
            height: "{data.height}",
            ..attributes,
            dangerous_inner_html: "{data.body}",
        }
    }
}

pub mod heroicons;
pub mod mdi;
